title: Creham
email: contact@creham.com
description: >- # this means to ignore newlines until "short_description:"
  Une équipe pluridisciplinaire pour vos projets d'étude, conseil, assistance à maîtrise d'ouvrage et maîtrise d'oeuvre.
short_description: Creham, urbanisme, paysage, sociologie et développement local
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.creham.com" # the base hostname & protocol for your site, e.g. http://example.com
color: eb5e03
lang: fr

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-coffeescript
  - jekyll-sitemap

sass:
  style: compressed

timezone: Europe/Paris
encoding: utf-8

collections:
  pages:
    output: true
    permalink: /:path

exclude: [
  "package.json",
  "package-lock.json",
  "webpack.config.js",
  "README.md",
  "Gemfile",
  "Gemfile.lock",
  "/node_modules"
]
