title: Creham
email: contact@creham.com
description: >- # this means to ignore newlines until "short_description:"
  Urbanisme, paysage, sociologie et développement local.
short_description: Une équipe pluridisciplinaire.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.creham.com" # the base hostname & protocol for your site, e.g. http://example.com
color: eb5e03
lang: fr

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-coffeescript

sass:
  style: compressed

timezone: Europe/Paris
encoding: utf-8

collections:
  pages:
    output: true
    permalink: /:path
