title: Créham
email: contact@creham.com
description: >- # this means to ignore newlines until the next property:
  Une équipe pluridisciplinaire pour vos projets d'étude, conseil, assistance à maîtrise d'ouvrage et maîtrise d'oeuvre.
short_description: Créham, urbanisme, paysage, sociologie et développement local
baseurl: "" # the subpath of your site, e.g. /blog (usefull if you have a github-pages subpath e.g. http://user.github.com/blog)
#url: "https://creham.com" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://creham.julesrx.fr" # the base hostname & protocol for your site, e.g. http://example.com
color: eb5e03
lang: fr

featured_link: "https://www.modalisa-enquete.com/grand_cognac_c/"
featured_html: >-
  <b>GRAND COGNAC : CONSULTATION DES SALARIÉS</b>
  <br>
  "Equilibre des temps de vie des salariés et parentalité en entreprise"

# Build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  - scope:
      path: "assets/img/slider"
    values:
      slider: true

collections:
  pages:
    output: true
    permalink: /:path
    sort_by: order

timezone: Europe/Paris
encoding: utf-8
