title: Creham
email: contact@creham.com
description: >- # this means to ignore newlines until "baseurl:"
  Une équipe pluridisciplinaire pour vos projets d'étude, conseil, assistance à maîtrise d'ouvrage et maîtrise d'oeuvre.
short_description: Creham, urbanisme, paysage, sociologie et développement local
baseurl: "" # the subpath of your site, e.g. /blog (usefull if you have a github-pages subpath e.g. http://user.github.com/blog)
#url: "https://creham.com" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://creham.julesrx.fr" # the base hostname & protocol for your site, e.g. http://example.com
color: eb5e03
lang: fr

# Build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  - scope:
      path: "assets/img/slider"
    values:
      slider: true

collections:
  pages:
    output: true
    permalink: /:path
    sort_by: order

timezone: Europe/Paris
encoding: utf-8
